const UI_ROW_HEIGHT = 30;
const UI_TEXT_SCALE = 0.9;

export const COLOR = { BACKGROUND: '#222' };
export const INCREMENTOR = { BUTTON_WIDTH: UI_ROW_HEIGHT, PADDING_INTRA: 5, TEXT_SIZE: UI_ROW_HEIGHT * UI_TEXT_SCALE };
export const UI = { MARGIN_TOP: 10, PADDING_INTER: 5, ROW_HEIGHT: UI_ROW_HEIGHT };
