const UI_ROW_HEIGHT = 30;
const UI_TEXT_SCALE = 0.9;

export const COLOR = { BACKGROUND: '#222' };
export const INCREMENTOR = { BUTTON_WIDTH: UI_ROW_HEIGHT, PADDING_INTRA: 5 };
export const UI = {
  MARGIN_LEFT: 10,
  MARGIN_TOP: 10,
  PADDING_INTER: 5,
  ROW_HEIGHT: UI_ROW_HEIGHT,
  TEXT_SIZE: UI_ROW_HEIGHT * UI_TEXT_SCALE,
};
export const USER_PARAMETERS = {
  FREQUENCY: {
    INITIAL: 1, MIN: 1, MAX: 10, INCREMENT: 1,
  },
};
export const POLYHEDRON = { RELATIVE_RADIUS: 0.4, RELATIVE_VERTEX_RADIUS: 0.025, RELATIVE_EDGE_RADIUS: 0.02 };
